large:
- ticker: 1COV.DE
  name: 1COV
  marketCap: null
- ticker: AAPL.OQ
  name: AAPL
  marketCap: null
- ticker: ABNB.OQ
  name: ABNB
  marketCap: null
- ticker: ABT.N
  name: ABT
  marketCap: null
- ticker: ACS.MC
  name: ACS
  marketCap: null
- ticker: ADBE.OQ
  name: ADBE
  marketCap: null
- ticker: ADM.N
  name: ADM
  marketCap: null
- ticker: ADP.OQ
  name: ADP
  marketCap: null
- ticker: ADS.DE
  name: ADS
  marketCap: null
- ticker: AHT.L
  name: AHT
  marketCap: null
- ticker: AIR.PA
  name: AIR
  marketCap: null
- ticker: ALV.DE
  name: ALV
  marketCap: null
- ticker: ALV.PA
  name: ALV
  marketCap: null
- ticker: AMD.OQ
  name: AMD
  marketCap: null
- ticker: AMGN.OQ
  name: AMGN
  marketCap: null
- ticker: AMZN.OQ
  name: AMZN
  marketCap: null
- ticker: ANA.MC
  name: ANA
  marketCap: null
- ticker: ASML.AS
  name: ASML
  marketCap: null
- ticker: ASML.OQ
  name: ASML
  marketCap: null
- ticker: AVGO.OQ
  name: AVGO
  marketCap: null
- ticker: AZN.L
  name: AZN
  marketCap: null
- ticker: AZN.N
  name: AZN
  marketCap: null
- ticker: BA.L
  name: BA
  marketCap: null
- ticker: BA.N
  name: BA
  marketCap: null
- ticker: BABA.N
  name: BABA
  marketCap: null
- ticker: BAC.N
  name: BAC
  marketCap: null
- ticker: BARC.L
  name: BARC
  marketCap: null
- ticker: BAS.DE
  name: BAS
  marketCap: null
- ticker: BAYN.DE
  name: BAYN
  marketCap: null
- ticker: BBVA.MC
  name: BBVA
  marketCap: null
- ticker: BDEV.L
  name: BDEV
  marketCap: null
- ticker: BIDU.OQ
  name: BIDU
  marketCap: null
- ticker: BKNG.OQ
  name: BKNG
  marketCap: null
- ticker: BLND.L
  name: BLND
  marketCap: null
- ticker: BMW.DE
  name: BMW
  marketCap: null
- ticker: BNPP.PA
  name: BNPP
  marketCap: null
- ticker: BP.L
  name: BP
  marketCap: null
- ticker: BT.L
  name: BT
  marketCap: null
- ticker: C.N
  name: C
  marketCap: null
- ticker: CAP.PA
  name: CAP
  marketCap: null
- ticker: CAT.N
  name: CAT
  marketCap: null
- ticker: CBKG.DE
  name: CBKG
  marketCap: null
- ticker: CCL.L
  name: CCL
  marketCap: null
- ticker: CHTR.OQ
  name: CHTR
  marketCap: null
- ticker: CMCSA.OQ
  name: CMCSA
  marketCap: null
- ticker: CNA.L
  name: CNA
  marketCap: null
- ticker: COST.OQ
  name: COST
  marketCap: null
- ticker: CPG.L
  name: CPG
  marketCap: null
- ticker: CRWD.OQ
  name: CRWD
  marketCap: null
- ticker: CS.PA
  name: CS
  marketCap: null
- ticker: CSCO.OQ
  name: CSCO
  marketCap: null
- ticker: CVS.N
  name: CVS
  marketCap: null
- ticker: DBK.DE
  name: DBK
  marketCap: null
- ticker: DE.N
  name: DE
  marketCap: null
- ticker: DGE.L
  name: DGE
  marketCap: null
- ticker: DHR.N
  name: DHR
  marketCap: null
- ticker: DIS.N
  name: DIS
  marketCap: null
- ticker: DTE.DE
  name: DTE
  marketCap: null
- ticker: EL.PA
  name: EL
  marketCap: null
- ticker: ENEL.MI
  name: ENEL
  marketCap: null
- ticker: ENI.MI
  name: ENI
  marketCap: null
- ticker: EONGn.DE
  name: EONGn
  marketCap: null
- ticker: EXPN.L
  name: EXPN
  marketCap: null
- ticker: EZJ.L
  name: EZJ
  marketCap: null
- ticker: FER.MC
  name: FER
  marketCap: null
- ticker: FLTR.L
  name: FLTR
  marketCap: null
- ticker: FME.DE
  name: FME
  marketCap: null
- ticker: FREG.DE
  name: FREG
  marketCap: null
- ticker: FRES.L
  name: FRES
  marketCap: null
- ticker: G.MI
  name: G
  marketCap: null
- ticker: GE.N
  name: GE
  marketCap: null
- ticker: GLE.PA
  name: GLE
  marketCap: null
- ticker: GLEN.L
  name: GLEN
  marketCap: null
- ticker: GOOG.OQ
  name: GOOG
  marketCap: null
- ticker: GOOGL.OQ
  name: GOOGL
  marketCap: null
- ticker: GS.N
  name: GS
  marketCap: null
- ticker: GSK.L
  name: GSK
  marketCap: null
- ticker: GSK.N
  name: GSK
  marketCap: null
- ticker: HAL.N
  name: HAL
  marketCap: null
- ticker: HD.N
  name: HD
  marketCap: null
- ticker: HLMA.L
  name: HLMA
  marketCap: null
- ticker: HON.N
  name: HON
  marketCap: null
- ticker: HSBA.L
  name: HSBA
  marketCap: null
- ticker: IAG.L
  name: IAG
  marketCap: null
- ticker: IBE.MC
  name: IBE
  marketCap: null
- ticker: IBM.N
  name: IBM
  marketCap: null
- ticker: IFX.DE
  name: IFX
  marketCap: null
- ticker: INTC.OQ
  name: INTC
  marketCap: null
- ticker: INTU.OQ
  name: INTU
  marketCap: null
- ticker: ISP.MI
  name: ISP
  marketCap: null
- ticker: ISRG.OQ
  name: ISRG
  marketCap: null
- ticker: ITX.MC
  name: ITX
  marketCap: null
- ticker: JD.L
  name: JD
  marketCap: null
- ticker: JD.OQ
  name: JD
  marketCap: null
- ticker: JNJ.N
  name: JNJ
  marketCap: null
- ticker: JPM.N
  name: JPM
  marketCap: null
- ticker: KER.PA
  name: KER
  marketCap: null
- ticker: KHC.OQ
  name: KHC
  marketCap: null
- ticker: KLAC.OQ
  name: KLAC
  marketCap: null
- ticker: KO.N
  name: KO
  marketCap: null
- ticker: LIN.DE
  name: LIN
  marketCap: null
- ticker: LLOY.L
  name: LLOY
  marketCap: null
- ticker: LLY.N
  name: LLY
  marketCap: null
- ticker: LOW.N
  name: LOW
  marketCap: null
- ticker: LRCX.OQ
  name: LRCX
  marketCap: null
- ticker: LVMH.PA
  name: LVMH
  marketCap: null
- ticker: MA.N
  name: MA
  marketCap: null
- ticker: MC.PA
  name: MC
  marketCap: null
- ticker: MCD.N
  name: MCD
  marketCap: null
- ticker: MDLZ.N
  name: MDLZ
  marketCap: null
- ticker: MDLZ.OQ
  name: MDLZ
  marketCap: null
- ticker: MKS.L
  name: MKS
  marketCap: null
- ticker: MMM.N
  name: MMM
  marketCap: null
- ticker: MNDI.L
  name: MNDI
  marketCap: null
- ticker: MO.N
  name: MO
  marketCap: null
- ticker: MONC.MI
  name: MONC
  marketCap: null
- ticker: MRK.DE
  name: MRK
  marketCap: null
- ticker: MRK.N
  name: MRK
  marketCap: null
- ticker: MRO.L
  name: MRO
  marketCap: null
- ticker: MS.N
  name: MS
  marketCap: null
- ticker: MSFT.OQ
  name: MSFT
  marketCap: null
- ticker: MU.OQ
  name: MU
  marketCap: null
- ticker: MUV2.DE
  name: MUV2
  marketCap: null
- ticker: NDA.DE
  name: NDA
  marketCap: null
- ticker: NDA.HE
  name: NDA
  marketCap: null
- ticker: NEE.N
  name: NEE
  marketCap: null
- ticker: NFLX.OQ
  name: NFLX
  marketCap: null
- ticker: NKE.N
  name: NKE
  marketCap: null
- ticker: NTES.OQ
  name: NTES
  marketCap: null
- ticker: NVDA.OQ
  name: NVDA
  marketCap: null
- ticker: NXT.L
  name: NXT
  marketCap: null
- ticker: OR.PA
  name: OR
  marketCap: null
- ticker: ORCL.N
  name: ORCL
  marketCap: null
- ticker: PDD.OQ
  name: PDD
  marketCap: null
- ticker: PEP.N
  name: PEP
  marketCap: null
- ticker: PEP.OQ
  name: PEP
  marketCap: null
- ticker: PFE.N
  name: PFE
  marketCap: null
- ticker: PFG.L
  name: PFG
  marketCap: null
- ticker: PG.N
  name: PG
  marketCap: null
- ticker: PHIA.AS
  name: PHIA
  marketCap: null
- ticker: PRU.L
  name: PRU
  marketCap: null
- ticker: PRY.MI
  name: PRY
  marketCap: null
- ticker: PSN.L
  name: PSN
  marketCap: null
- ticker: PUB.PA
  name: PUB
  marketCap: null
- ticker: PYPL.OQ
  name: PYPL
  marketCap: null
- ticker: QCOM.OQ
  name: QCOM
  marketCap: null
- ticker: RDSA.AS
  name: RDSA
  marketCap: null
- ticker: REL.L
  name: REL
  marketCap: null
- ticker: REP.MC
  name: REP
  marketCap: null
- ticker: RMS.PA
  name: RMS
  marketCap: null
- ticker: RRTL.DE
  name: RRTL
  marketCap: null
- ticker: RTX.N
  name: RTX
  marketCap: null
- ticker: RWE.DE
  name: RWE
  marketCap: null
- ticker: SAN.MC
  name: SAN
  marketCap: null
- ticker: SAN.PA
  name: SAN
  marketCap: null
- ticker: SAP.DE
  name: SAP
  marketCap: null
- ticker: SBUX.OQ
  name: SBUX
  marketCap: null
- ticker: SDR.L
  name: SDR
  marketCap: null
- ticker: SGEN.OQ
  name: SGEN
  marketCap: null
- ticker: SGO.PA
  name: SGO
  marketCap: null
- ticker: SHEL.L
  name: SHEL
  marketCap: null
- ticker: SIE.DE
  name: SIE
  marketCap: null
- ticker: SMT.L
  name: SMT
  marketCap: null
- ticker: SN.L
  name: SN
  marketCap: null
- ticker: SPM.MI
  name: SPM
  marketCap: null
- ticker: SPX.L
  name: SPX
  marketCap: null
- ticker: SSE.L
  name: SSE
  marketCap: null
- ticker: STLA.MI
  name: STLA
  marketCap: null
- ticker: SU.PA
  name: SU
  marketCap: null
- ticker: SVS.L
  name: SVS
  marketCap: null
- ticker: SYK.N
  name: SYK
  marketCap: null
- ticker: TEF.MC
  name: TEF
  marketCap: null
- ticker: TEN.MI
  name: TEN
  marketCap: null
- ticker: TIT.MI
  name: TIT
  marketCap: null
- ticker: TMO.N
  name: TMO
  marketCap: null
- ticker: TMUS.OQ
  name: TMUS
  marketCap: null
- ticker: TSLA.OQ
  name: TSLA
  marketCap: null
- ticker: TW.L
  name: TW
  marketCap: null
- ticker: TXN.OQ
  name: TXN
  marketCap: null
- ticker: UBER.N
  name: UBER
  marketCap: null
- ticker: UCG.MI
  name: UCG
  marketCap: null
- ticker: ULVR.L
  name: ULVR
  marketCap: null
- ticker: UNH.N
  name: UNH
  marketCap: null
- ticker: UNP.N
  name: UNP
  marketCap: null
- ticker: UPS.N
  name: UPS
  marketCap: null
- ticker: UU.L
  name: UU
  marketCap: null
- ticker: V.N
  name: V
  marketCap: null
- ticker: VOW3.DE
  name: VOW3
  marketCap: null
- ticker: VZ.N
  name: VZ
  marketCap: null
- ticker: WCR.PA
  name: WCR
  marketCap: null
- ticker: WDAY.OQ
  name: WDAY
  marketCap: null
- ticker: WEIR.L
  name: WEIR
  marketCap: null
- ticker: WMT.N
  name: WMT
  marketCap: null
- ticker: WPG.L
  name: WPG
  marketCap: null
- ticker: WPP.L
  name: WPP
  marketCap: null
- ticker: WRT1V.HE
  name: WRT1V
  marketCap: null
- ticker: WTB.L
  name: WTB
  marketCap: null
- ticker: XOM.N
  name: XOM
  marketCap: null
- ticker: ZM.OQ
  name: ZM
  marketCap: null
- ticker: ZS.OQ
  name: ZS
  marketCap: null
mid:
- ticker: AEP.OQ
  name: AEP
  marketCap: null
- ticker: CGC.N
  name: CGC
  marketCap: null
- ticker: CPRT.OQ
  name: CPRT
  marketCap: null
- ticker: CQQQ.OQ
  name: CQQQ
  marketCap: null
- ticker: DOGE.OQ
  name: DOGE
  marketCap: null
- ticker: DXCM.OQ
  name: DXCM
  marketCap: null
- ticker: EXC.OQ
  name: EXC
  marketCap: null
- ticker: FAST.OQ
  name: FAST
  marketCap: null
- ticker: FXI.N
  name: FXI
  marketCap: null
- ticker: ILMN.OQ
  name: ILMN
  marketCap: null
- ticker: JCI.N
  name: JCI
  marketCap: null
- ticker: KWEB.OQ
  name: KWEB
  marketCap: null
- ticker: MAR.OQ
  name: MAR
  marketCap: null
- ticker: MCHI.N
  name: MCHI
  marketCap: null
- ticker: NIO.N
  name: NIO
  marketCap: null
- ticker: OXY.N
  name: OXY
  marketCap: null
- ticker: PSX.N
  name: PSX
  marketCap: null
- ticker: PTON.OQ
  name: PTON
  marketCap: null
- ticker: REGN.OQ
  name: REGN
  marketCap: null
- ticker: TCEHY.OQ
  name: TCEHY
  marketCap: null
- ticker: ZTS.N
  name: ZTS
  marketCap: null
small: []
unclassified:
- ticker: AAL.L
  name: AAL
  marketCap: null
- ticker: AAL.OQ
  name: AAL
  marketCap: null
- ticker: ABBV.N
  name: ABBV
  marketCap: null
- ticker: ABF.L
  name: ABF
  marketCap: null
- ticker: ABI.BR
  name: ABI
  marketCap: null
- ticker: ADI.OQ
  name: ADI
  marketCap: null
- ticker: ADSK.OQ
  name: ADSK
  marketCap: null
- ticker: ADYEN.AS
  name: ADYEN
  marketCap: null
- ticker: AEX.AS
  name: AEX
  marketCap: null
- ticker: AGN.AS
  name: AGN
  marketCap: null
- ticker: AIG.N
  name: AIG
  marketCap: null
- ticker: AIRF.PA
  name: AIRF
  marketCap: null
- ticker: AKZA.AS
  name: AKZA
  marketCap: null
- ticker: ALGN.OQ
  name: ALGN
  marketCap: null
- ticker: ALL.N
  name: ALL
  marketCap: null
- ticker: ALVG.DE
  name: ALVG
  marketCap: null
- ticker: AMAT.OQ
  name: AMAT
  marketCap: null
- ticker: ANSS.OQ
  name: ANSS
  marketCap: null
- ticker: ARGX.BR
  name: ARGX
  marketCap: null
- ticker: ATVI.OQ
  name: ATVI
  marketCap: null
- ticker: AXP.N
  name: AXP
  marketCap: null
- ticker: BDX.N
  name: BDX
  marketCap: null
- ticker: BEIG.DE
  name: BEIG
  marketCap: null
- ticker: BHP.L
  name: BHP
  marketCap: null
- ticker: BIIB.OQ
  name: BIIB
  marketCap: null
- ticker: BNP.PA
  name: BNP
  marketCap: null
- ticker: BPOST.BR
  name: BPOST
  marketCap: null
- ticker: BRBY.L
  name: BRBY
  marketCap: null
- ticker: CB.N
  name: CB
  marketCap: null
- ticker: CDNS.OQ
  name: CDNS
  marketCap: null
- ticker: CDW.OQ
  name: CDW
  marketCap: null
- ticker: CERN.OQ
  name: CERN
  marketCap: null
- ticker: CHKP.OQ
  name: CHKP
  marketCap: null
- ticker: CLNX.MI
  name: CLNX
  marketCap: null
- ticker: COFB.BR
  name: COFB
  marketCap: null
- ticker: COLR.BR
  name: COLR
  marketCap: null
- ticker: CONG.DE
  name: CONG
  marketCap: null
- ticker: CRH.L
  name: CRH
  marketCap: null
- ticker: CRON.OQ
  name: CRON
  marketCap: null
- ticker: CTAS.OQ
  name: CTAS
  marketCap: null
- ticker: CTSH.OQ
  name: CTSH
  marketCap: null
- ticker: CVX.N
  name: CVX
  marketCap: null
- ticker: DANO.PA
  name: DANO
  marketCap: null
- ticker: DD.N
  name: DD
  marketCap: null
- ticker: DELL.N
  name: DELL
  marketCap: null
- ticker: DLTR.OQ
  name: DLTR
  marketCap: null
- ticker: DOCU.OQ
  name: DOCU
  marketCap: null
- ticker: DOW.N
  name: DOW
  marketCap: null
- ticker: DSM.AS
  name: DSM
  marketCap: null
- ticker: EA.OQ
  name: EA
  marketCap: null
- ticker: EBAY.OQ
  name: EBAY
  marketCap: null
- ticker: EBR.BR
  name: EBR
  marketCap: null
- ticker: EMR.N
  name: EMR
  marketCap: null
- ticker: ENGI.PA
  name: ENGI
  marketCap: null
- ticker: F.N
  name: F
  marketCap: null
- ticker: FB.OQ
  name: FB
  marketCap: null
- ticker: FCA.MI
  name: FCA
  marketCap: null
- ticker: FCX.N
  name: FCX
  marketCap: null
- ticker: FDX.N
  name: FDX
  marketCap: null
- ticker: FISV.OQ
  name: FISV
  marketCap: null
- ticker: FLOW.AS
  name: FLOW
  marketCap: null
- ticker: FORTUM.HE
  name: FORTUM
  marketCap: null
- ticker: FOX.OQ
  name: FOX
  marketCap: null
- ticker: FTNT.OQ
  name: FTNT
  marketCap: null
- ticker: GBLB.BR
  name: GBLB
  marketCap: null
- ticker: GD.N
  name: GD
  marketCap: null
- ticker: GILD.OQ
  name: GILD
  marketCap: null
- ticker: GM.N
  name: GM
  marketCap: null
- ticker: GRF.MC
  name: GRF
  marketCap: null
- ticker: HAS.OQ
  name: HAS
  marketCap: null
- ticker: HEI.DE
  name: HEI
  marketCap: null
- ticker: HEIA.AS
  name: HEIA
  marketCap: null
- ticker: HEIG.DE
  name: HEIG
  marketCap: null
- ticker: HEN3.DE
  name: HEN3
  marketCap: null
- ticker: HL.L
  name: HL
  marketCap: null
- ticker: HLT.N
  name: HLT
  marketCap: null
- ticker: HPQ.N
  name: HPQ
  marketCap: null
- ticker: HSIC.OQ
  name: HSIC
  marketCap: null
- ticker: ICP.L
  name: ICP
  marketCap: null
- ticker: IDXX.OQ
  name: IDXX
  marketCap: null
- ticker: INCY.OQ
  name: INCY
  marketCap: null
- ticker: INGA.AS
  name: INGA
  marketCap: null
- ticker: ITV.L
  name: ITV
  marketCap: null
- ticker: JET2.L
  name: JET2
  marketCap: null
- ticker: K.N
  name: K
  marketCap: null
- ticker: KBC.BR
  name: KBC
  marketCap: null
- ticker: KDP.OQ
  name: KDP
  marketCap: null
- ticker: KGF.L
  name: KGF
  marketCap: null
- ticker: KONE.HE
  name: KONE
  marketCap: null
- ticker: KPN.AS
  name: KPN
  marketCap: null
- ticker: LAND.L
  name: LAND
  marketCap: null
- ticker: LDO.MI
  name: LDO
  marketCap: null
- ticker: LHA.DE
  name: LHA
  marketCap: null
- ticker: LHAG.DE
  name: LHAG
  marketCap: null
- ticker: LMT.N
  name: LMT
  marketCap: null
- ticker: LR.PA
  name: LR
  marketCap: null
- ticker: LULU.OQ
  name: LULU
  marketCap: null
- ticker: MAP.MC
  name: MAP
  marketCap: null
- ticker: MCHP.OQ
  name: MCHP
  marketCap: null
- ticker: MELI.OQ
  name: MELI
  marketCap: null
- ticker: MNST.OQ
  name: MNST
  marketCap: null
- ticker: MRNA.OQ
  name: MRNA
  marketCap: null
- ticker: MRVL.OQ
  name: MRVL
  marketCap: null
- ticker: MT.AS
  name: MT
  marketCap: null
- ticker: MTCH.OQ
  name: MTCH
  marketCap: null
- ticker: MTS.MC
  name: MTS
  marketCap: null
- ticker: NESTE.HE
  name: NESTE
  marketCap: null
- ticker: NG.L
  name: NG
  marketCap: null
- ticker: NN.AS
  name: NN
  marketCap: null
- ticker: NOC.N
  name: NOC
  marketCap: null
- ticker: NVO.N
  name: NVO
  marketCap: null
- ticker: NXPI.OQ
  name: NXPI
  marketCap: null
- ticker: OCDO.L
  name: OCDO
  marketCap: null
- ticker: OKTA.OQ
  name: OKTA
  marketCap: null
- ticker: OML.L
  name: OML
  marketCap: null
- ticker: ORIONB.HE
  name: ORIONB
  marketCap: null
- ticker: ORLY.OQ
  name: ORLY
  marketCap: null
- ticker: PAYX.OQ
  name: PAYX
  marketCap: null
- ticker: PCAR.OQ
  name: PCAR
  marketCap: null
- ticker: PNC.N
  name: PNC
  marketCap: null
- ticker: POLY.L
  name: POLY
  marketCap: null
- ticker: PROX.BR
  name: PROX
  marketCap: null
- ticker: PUMG.DE
  name: PUMG
  marketCap: null
- ticker: RACE.MI
  name: RACE
  marketCap: null
- ticker: RACE.N
  name: RACE
  marketCap: null
- ticker: RAND.AS
  name: RAND
  marketCap: null
- ticker: REE.MC
  name: REE
  marketCap: null
- ticker: RIO.L
  name: RIO
  marketCap: null
- ticker: ROST.OQ
  name: ROST
  marketCap: null
- ticker: RWEG.DE
  name: RWEG
  marketCap: null
- ticker: SAMPO.HE
  name: SAMPO
  marketCap: null
- ticker: SAPG.DE
  name: SAPG
  marketCap: null
- ticker: SBRY.L
  name: SBRY
  marketCap: null
- ticker: SGRE.MC
  name: SGRE
  marketCap: null
- ticker: SHL.DE
  name: SHL
  marketCap: null
- ticker: SIRI.OQ
  name: SIRI
  marketCap: null
- ticker: SMIN.L
  name: SMIN
  marketCap: null
- ticker: SNPS.OQ
  name: SNPS
  marketCap: null
- ticker: SNY.N
  name: SNY
  marketCap: null
- ticker: SO.N
  name: SO
  marketCap: null
- ticker: SOGN.PA
  name: SOGN
  marketCap: null
- ticker: SOLB.BR
  name: SOLB
  marketCap: null
- ticker: SONY.N
  name: SONY
  marketCap: null
- ticker: SPLK.OQ
  name: SPLK
  marketCap: null
- ticker: STM.PA
  name: STM
  marketCap: null
- ticker: SWKS.OQ
  name: SWKS
  marketCap: null
- ticker: T.N
  name: T
  marketCap: null
- ticker: TCOM.OQ
  name: TCOM
  marketCap: null
- ticker: TEAM.OQ
  name: TEAM
  marketCap: null
- ticker: TELIA1.HE
  name: TELIA1
  marketCap: null
- ticker: TEVA.P
  name: TEVA
  marketCap: null
- ticker: TKWY.AS
  name: TKWY
  marketCap: null
- ticker: TNET.BR
  name: TNET
  marketCap: null
- ticker: TOTF.PA
  name: TOTF
  marketCap: null
- ticker: TRN.L
  name: TRN
  marketCap: null
- ticker: TRN.MI
  name: TRN
  marketCap: null
- ticker: TSCO.L
  name: TSCO
  marketCap: null
- ticker: TUI.L
  name: TUI
  marketCap: null
- ticker: TWTR.N
  name: TWTR
  marketCap: null
- ticker: ULTA.OQ
  name: ULTA
  marketCap: null
- ticker: UMIC.BR
  name: UMIC
  marketCap: null
- ticker: UNA.AS
  name: UNA
  marketCap: null
- ticker: UNI.MI
  name: UNI
  marketCap: null
- ticker: UP.HE
  name: UP
  marketCap: null
- ticker: UPM.HE
  name: UPM
  marketCap: null
- ticker: USB.N
  name: USB
  marketCap: null
- ticker: UTX.N
  name: UTX
  marketCap: null
- ticker: VALMT.HE
  name: VALMT
  marketCap: null
- ticker: VAR1.DE
  name: VAR1
  marketCap: null
- ticker: VGP.BR
  name: VGP
  marketCap: null
- ticker: VIE.PA
  name: VIE
  marketCap: null
- ticker: VIV.PA
  name: VIV
  marketCap: null
- ticker: VOD.L
  name: VOD
  marketCap: null
- ticker: VPK.AS
  name: VPK
  marketCap: null
- ticker: VRSK.OQ
  name: VRSK
  marketCap: null
- ticker: VRTX.OQ
  name: VRTX
  marketCap: null
- ticker: VTY.L
  name: VTY
  marketCap: null
- ticker: WBA.N
  name: WBA
  marketCap: null
- ticker: WBA.OQ
  name: WBA
  marketCap: null
- ticker: WDP.AS
  name: WDP
  marketCap: null
- ticker: WDP.BR
  name: WDP
  marketCap: null
- ticker: WFC.N
  name: WFC
  marketCap: null
- ticker: WHR.L
  name: WHR
  marketCap: null
- ticker: WHR.N
  name: WHR
  marketCap: null
- ticker: WIZZ.L
  name: WIZZ
  marketCap: null
- ticker: WKL.AS
  name: WKL
  marketCap: null
- ticker: XEL.N
  name: XEL
  marketCap: null
- ticker: XEL.OQ
  name: XEL
  marketCap: null
- ticker: ZALG.DE
  name: ZALG
  marketCap: null
